apiVersion: v1
kind: Pod
metadata: 
  name: nginx
  labels:
    app: nginx
    tier: frontend
spec: 
  containers:
  - name: nginx
    image: nginx

#Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
#pod/nginx configured

#kubectl create -f temp0.yaml
#OR
#kubectl apply -f temp0.yaml

# Use apply if you want to use kubectl apply to modify the resource
#For useing create such that you can apply modifications, use kubectl create --save-config